version: '3'

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: ./front-end.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "8080:8080"

  test-microservice:
    build:
      context: ./test-microservice
      dockerfile: ./test-microservice.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
#      dbType: "postgres"
      DSN: "host=postgres port=5432 user=postgres password=password dbname=urls sslmode=disable timezone=UTC connect_timeout=5"
      dbURL: "postgres://postgres:password@postgres:5432/urls?sslmode=disable"
      migrationPath: "file:///app"

  postgres:
    image: 'postgres:14.2-alpine'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: urls
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
