version: '3'

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: ./front-end.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "8080:8080"

  test-microservice:
    build:
      context: ./test-microservice
      dockerfile: ./test-microservice.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
